-- 코드를 입력하세요
SELECT DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
    ONLINE_SALE.PRODUCT_ID, 
    ONLINE_SALE.USER_ID,
    ONLINE_SALE.SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(ONLINE_SALE.SALES_DATE) = 2022
    AND MONTH(ONLINE_SALE.SALES_DATE) = 3
UNION ALL
SELECT DATE_FORMAT(OFFLINE_SALE.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
    OFFLINE_SALE.PRODUCT_ID, 
    NULL AS USER_ID,
    OFFLINE_SALE.SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(OFFLINE_SALE.SALES_DATE) = 2022
    AND MONTH(OFFLINE_SALE.SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID